"""Database models and connection for BTC 5-min trading bot."""
from datetime import datetime
from typing import Optional
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Boolean, JSON, Text, text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy import inspect
import enum

from backend.config import settings

engine = create_engine(
    settings.DATABASE_URL,
    connect_args={"check_same_thread": False} if "sqlite" in settings.DATABASE_URL else {}
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


class Trade(Base):
    """Simulated trades for tracking P&L."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, index=True)
    signal_id = Column(Integer, index=True)
    market_ticker = Column(String, index=True)
    platform = Column(String)
    event_slug = Column(String, nullable=True)
    market_type = Column(String, default="btc", index=True)  # "btc" or "weather"

    # Trade details
    direction = Column(String)  # "up" or "down"
    entry_price = Column(Float)
    size = Column(Float)
    timestamp = Column(DateTime, default=datetime.utcnow)

    # Settlement
    settled = Column(Boolean, default=False)
    settlement_time = Column(DateTime, nullable=True)
    settlement_value = Column(Float, nullable=True)  # 1.0=Up won, 0.0=Down won
    result = Column(String, default="pending")  # pending, win, loss
    pnl = Column(Float, nullable=True)

    # Model performance tracking
    model_probability = Column(Float)
    market_price_at_entry = Column(Float)
    edge_at_entry = Column(Float)


class BtcPriceSnapshot(Base):
    """Cached BTC prices for momentum calculation."""
    __tablename__ = "btc_price_snapshots"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    price = Column(Float)
    source = Column(String, default="coingecko")


class BotState(Base):
    """Bot state and statistics."""
    __tablename__ = "bot_state"

    id = Column(Integer, primary_key=True)
    bankroll = Column(Float, default=10000.0)
    total_trades = Column(Integer, default=0)
    winning_trades = Column(Integer, default=0)
    total_pnl = Column(Float, default=0.0)
    last_run = Column(DateTime, nullable=True)
    is_running = Column(Boolean, default=False)


class Signal(Base):
    """Trading signals generated by the bot."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, index=True)
    market_ticker = Column(String, index=True)
    platform = Column(String)
    market_type = Column(String, default="btc", index=True)  # "btc" or "weather"
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)

    direction = Column(String)
    model_probability = Column(Float)
    market_price = Column(Float)
    edge = Column(Float)
    confidence = Column(Float)

    kelly_fraction = Column(Float)
    suggested_size = Column(Float)

    sources = Column(JSON)
    reasoning = Column(String)

    executed = Column(Boolean, default=False)

    # Calibration tracking — filled after settlement
    actual_outcome = Column(String, nullable=True)    # "up" or "down" — actual market result
    outcome_correct = Column(Boolean, nullable=True)   # did our direction prediction match?
    settlement_value = Column(Float, nullable=True)     # 1.0=UP won, 0.0=DOWN won
    settled_at = Column(DateTime, nullable=True)        # when we recorded the outcome


class AILog(Base):
    """Log of all AI API calls."""
    __tablename__ = "ai_logs"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    provider = Column(String, index=True)
    model = Column(String)

    prompt = Column(String)
    response = Column(String)
    call_type = Column(String, index=True)

    latency_ms = Column(Float)
    tokens_used = Column(Integer)
    cost_usd = Column(Float)

    related_market = Column(String, nullable=True)
    success = Column(Boolean, default=True)
    error = Column(String, nullable=True)


class ScanLog(Base):
    """Log of each market scan run."""
    __tablename__ = "scan_logs"

    id = Column(Integer, primary_key=True, index=True)
    run_id = Column(String, unique=True, index=True)
    started_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    categories_scanned = Column(JSON)
    platforms_scanned = Column(JSON)

    markets_found = Column(Integer, default=0)
    signals_generated = Column(Integer, default=0)
    trades_executed = Column(Integer, default=0)

    ai_calls_made = Column(Integer, default=0)
    ai_cost_usd = Column(Float, default=0.0)

    success = Column(Boolean, default=True)
    error = Column(String, nullable=True)


class LiveSignal(Base):
    __tablename__ = "live_signals"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Signal identification
    ticker = Column(String, nullable=False, index=True)
    signal_type = Column(String, nullable=False)  # T-above, B-above, B-below
    city = Column(String, nullable=False)
    target_date = Column(String, nullable=False)
    threshold_f = Column(Float, nullable=False)

    # GFS forecast data
    gfs_mean = Column(Float, nullable=False)
    gfs_std = Column(Float, nullable=False)
    gfs_distance = Column(Float, nullable=False)

    # Market prices at time of signal
    yes_price_cents = Column(Integer, nullable=False)
    no_price_cents = Column(Integer, nullable=False)

    # Signal metrics
    historical_win_rate = Column(Float, nullable=False)
    expected_value = Column(Float, nullable=False)
    confidence_score = Column(Float, nullable=False)
    suggested_size = Column(Float, nullable=False)

    # Timing
    signal_fired_at = Column(DateTime, default=datetime.utcnow)

    # Outcome (filled in after settlement)
    actual_result = Column(String, nullable=True)   # "yes" or "no"
    signal_correct = Column(Boolean, nullable=True)
    profit_loss = Column(Float, nullable=True)
    settled_at = Column(DateTime, nullable=True)

    # Raw reasoning string for debugging
    reasoning = Column(Text, nullable=True)


class Btc15mSignal(Base):
    """KXBTC15M (Kalshi 15-min BTC) signal generated by the ROMA pipeline.

    One row per pipeline cycle that produced an actionable signal (or PASS
    when KXBTC15M_SEND_PASS_ALERTS is True). Columns track the full pipeline
    output so we can backtest model calibration after settlement.
    """
    __tablename__ = "btc15m_signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)

    # Market identity
    market_ticker = Column(String, index=True, nullable=False)
    event_ticker = Column(String, index=True)
    floor_strike = Column(Float, nullable=False)
    close_time = Column(DateTime, nullable=True)

    # Inputs at signal time
    spot = Column(Float, nullable=False)
    yes_ask = Column(Float)
    yes_bid = Column(Float)
    no_ask = Column(Float)
    no_bid = Column(Float)
    volume = Column(Float)
    market_implied_p = Column(Float)

    # Model output
    p_yes = Column(Float, nullable=False)
    edge = Column(Float, nullable=False)
    recommendation = Column(String, nullable=False)  # BUY_YES | BUY_NO | PASS
    confidence = Column(Float)

    # Sizing
    contracts = Column(Integer, default=0)
    notional_usd = Column(Float, default=0.0)
    kelly_fraction = Column(Float, default=0.0)

    # Reasoning artifacts
    sentiment_label = Column(String)
    sentiment_score = Column(Float)
    thesis = Column(Text)
    key_drivers = Column(JSON)
    risk_reasons = Column(JSON)

    # Outcome — filled after settlement
    settled = Column(Boolean, default=False, index=True)
    settled_at = Column(DateTime, nullable=True)
    settlement_value = Column(Float, nullable=True)   # 1.0 = YES won
    signal_correct = Column(Boolean, nullable=True)
    realized_pnl = Column(Float, nullable=True)
    auto_executed = Column(Boolean, default=False)


class ForecastHistory(Base):
    __tablename__ = "forecast_history"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Identification
    city_key = Column(String, nullable=False, index=True)
    station_id = Column(String, nullable=False)
    target_date = Column(String, nullable=False)

    # Forecast values
    mean_high = Column(Float, nullable=False)
    std_high = Column(Float, nullable=False)
    num_members = Column(Integer, nullable=False)
    models_used = Column(String, nullable=True)   # JSON string of model list
    member_highs = Column(String, nullable=True)  # JSON string of individual forecasts

    # Timing
    forecast_source = Column(String, nullable=False)  # "minutetemp" or "icon_eps"
    logged_at = Column(DateTime, default=datetime.utcnow, index=True)


def init_db():
    """Initialize database tables."""
    Base.metadata.create_all(bind=engine)
    ensure_schema()


def ensure_schema():
    """Ensure newer schema fields exist even if migration wasn't run."""
    inspector = inspect(engine)
    try:
        columns = [col["name"] for col in inspector.get_columns("trades")]
    except Exception:
        return

    if "event_slug" not in columns:
        stmt = "ALTER TABLE trades ADD COLUMN event_slug VARCHAR"
        if engine.dialect.name not in ("sqlite", "mysql"):
            stmt = "ALTER TABLE trades ADD COLUMN IF NOT EXISTS event_slug VARCHAR"

        with engine.connect() as conn:
            with conn.begin():
                conn.execute(text(stmt))

    if "market_type" not in columns:
        with engine.connect() as conn:
            with conn.begin():
                conn.execute(text("ALTER TABLE trades ADD COLUMN market_type VARCHAR DEFAULT 'btc'"))

    # Add calibration columns to signals table
    try:
        signal_columns = [col["name"] for col in inspector.get_columns("signals")]
    except Exception:
        signal_columns = []

    if signal_columns:
        with engine.connect() as conn:
            for col, coltype in [
                ("actual_outcome", "TEXT"),
                ("outcome_correct", "BOOLEAN"),
                ("settlement_value", "FLOAT"),
                ("settled_at", "DATETIME"),
                ("market_type", "VARCHAR DEFAULT 'btc'"),
            ]:
                if col not in signal_columns:
                    try:
                        with conn.begin():
                            conn.execute(text(f"ALTER TABLE signals ADD COLUMN {col} {coltype}"))
                    except Exception:
                        pass  # column already exists


def get_db():
    """Get database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
